### ISSUE TITLE
API timeout?

### ISSUE THREAD

**Issue by ThePatricide** [Cadsters/acv-hass-component#13]
Could it be that the API is down? The calendar still works in the ACV app, but HASS gives the following error:

This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/acv/sensor.py:143
Integration: acv (documentation)
First occurred: 9:47:15 AM (1 occurrences)
Last logged: 9:47:15 AM

Update for sensor.vandaag fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f604cb24790>: Failed to establish a new connection: [Errno 110] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wasteapi.ximmio.com', port=443): Max retries exceeded with url: /api/GetCalendar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f604cb24790>: Failed to establish a new connection: [Errno 110] Operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/acv/sensor.py", line 139, in update
    pickup_calendar = self._get_pickup_calendar(address_id)
  File "/config/custom_components/acv/sensor.py", line 174, in _get_pickup_calendar
    response = self._do_post_request('GetCalendar', data)
  File "/config/custom_components/acv/sensor.py", line 153, in _do_post_request
    response = requests.post(
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='wasteapi.ximmio.com', port=443): Max retries exceeded with url: /api/GetCalendar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f604cb24790>: Failed to establish a new connection: [Errno 110] Operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 316, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/acv/sensor.py", line 248, in update
    self._reader.update()
  File "/config/custom_components/acv/sensor.py", line 143, in update
    raise WasteApiException(
custom_components.acv.sensor.WasteApiException: ('Error occurred while fetching data: %r', ConnectionError(MaxRetryError("HTTPSConnectionPool(host='wasteapi.ximmio.com', port=443): Max retries exceeded with url: /api/GetCalendar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f604cb24790>: Failed to establish a new connection: [Errno 110] Operation timed out'))")))

**Comment by Cadsters** [comment]
I've got no issues retrieving data from the api.
Have u  checked https://acv-afvalkalender.nl in your browser?
Did you install the latest version v0.24.2?

**Comment by ThePatricide** [comment]
At first that gave me a timeout a couple of times in the browser as well, but it seems to be working again. Thanks!

**Comment by ThePatricide** [comment]
I ran into the issue again. It seems like when there is a timeout, there is no retry. As after I restarted HASS, it all worked perfectly again, but all sensors had been having status 'unknown' for 3 days straight. Is that something that might be added?

**Comment by Cadsters** [comment]
And again....
I've got no issues retrieving data from the api.
Have u checked https://acv-afvalkalender.nl in your browser (firefox, chrome)?
Worth mentioning that when you restart hass many times in a short time, you might get blocked by the api.
Without any details/logs i cannot help you.

**Comment by ThePatricide** [comment]
Yeah that website works without problem. But probably times out sometimes. What logs and details would you like to have? Then I'll include them next time it happens.

**Comment by Cadsters** [comment]
Please share your config for the acv-intergration and your hass-log.
Be sure you have this in your configuration.yaml:
```
logger:
  default: error
  logs:
    custom_components.acv: debug
```

**Comment by ThePatricide** [comment]
Thanks will do, will report back once it happens again.

**Comment by ThePatricide** [comment]
The following appeared twice in the logs:
`2021-05-17 00:00:14 DEBUG (SyncWorker_2) [custom_components.acv.sensor] Updating waste collection dates using Rest API
2021-05-17 00:00:24 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.afval_vandaag is taking over 10 seconds
2021-05-17 00:00:24 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'power_outage_memory' when rendering '{{ value_json.power_outage_memory }}'
2021-05-17 00:00:44 WARNING (MainThread) [homeassistant.components.sensor] Updating acv sensor took longer than the scheduled update interval 0:00:30
2021-05-17 00:01:14 WARNING (MainThread) [homeassistant.components.sensor] Updating acv sensor took longer than the scheduled update interval 0:00:30
2021-05-17 00:01:24 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'power_outage_memory' when rendering '{{ value_json.power_outage_memory }}'
2021-05-17 00:01:44 WARNING (MainThread) [homeassistant.components.sensor] Updating acv sensor took longer than the scheduled update interval 0:00:30
2021-05-17 00:02:14 WARNING (MainThread) [homeassistant.components.sensor] Updating acv sensor took longer than the scheduled update interval 0:00:30
2021-05-17 00:02:23 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.afval_vandaag fails
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
conn = connection.create_connection(
File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
raise err
File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
sock.connect(sa)
TimeoutError: [Errno 110] Operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
self._validate_conn(conn)
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
conn.connect()
File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
conn = self._new_conn()
File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f35034d7f40>: Failed to establish a new connection: [Errno 110] Operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wasteapi.ximmio.com', port=443): Max retries exceeded with url: /api/FetchAdress (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f35034d7f40>: Failed to establish a new connection: [Errno 110] Operation timed out'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/acv/sensor.py", line 139, in update
address_id = self._find_unique_address_id()
File "/config/custom_components/acv/sensor.py", line 164, in _find_unique_address_id
response = self._do_post_request('FetchAdress', data)
File "/config/custom_components/acv/sensor.py", line 154, in _do_post_request
response = requests.post(
File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 119, in post
return request('post', url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='wasteapi.ximmio.com', port=443): Max retries exceeded with url: /api/FetchAdress (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f35034d7f40>: Failed to establish a new connection: [Errno 110] Operation timed out'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 316, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_device_update
await task
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/acv/sensor.py", line 249, in update
self._reader.update()
File "/config/custom_components/acv/sensor.py", line 144, in update
raise WasteApiException(
custom_components.acv.sensor.WasteApiException: ('Error occurred while fetching data: %r', ConnectionError(MaxRetryError("HTTPSConnectionPool(host='wasteapi.ximmio.com', port=443): Max retries exceeded with url: /api/FetchAdress (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f35034d7f40>: Failed to establish a new connection: [Errno 110] Operation timed out'))")))`

My computer can reach these addresses fine, but maybe the VM at some point doesn't anymore? It always works after a restart but the next day or so it seems not to be able to connect anymore. 

Config:
  - platform: acv
    postcode: 1111AA
    housenumber: 1
    resources:
      - today
      - tomorrow
      - grey
      - green
      - paper
      - packages
      - textile

**Comment by Cadsters** [comment]
I'm sorry to hear that the intergration is not working for you.  I received no other messages and have no issues with the intergation in my config so susspect that something is not quite right in your config. 
I see in your last log "Template variable warning: 'dict object' has no attribute 'power_outage_memory' when rendering", could this be the cause? 
If you are running hass on a rpi make sure your powersuply is sufficient.
