### ISSUE TITLE
Afval Vandaag en Morgen blijft op Geen staan

### ISSUE THREAD

**Issue by mvdveek** [Cadsters/acv-hass-component#15]
Laatst de integratie toegevoegd, maar deze geeft geen waarden terug.
Sensors staan allemaal op Unknown.

Als ik in de log kijk vind ik het volgende terug:
```
2022-03-09 08:38:41 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.afval_vandaag fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 535, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 744, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/acv/sensor.py", line 241, in update
    self._reader.update()
  File "/config/custom_components/acv/sensor.py", line 131, in update
    address_id = self._find_unique_address_id()
  File "/config/custom_components/acv/sensor.py", line 157, in _find_unique_address_id
    return response['dataList'][0]['UniqueId']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Cadsters** [comment]
Hi, strange,  because all works for me.
Can you show me your config for this intergation?

**Comment by Cadsters** [comment]
I assume this issue is solved because i got no response to my question for more information.
