### ISSUE TITLE
Update for sensor.afval_pmd fails

### ISSUE THREAD

**Issue by Cadsters** [Cadsters/acv-hass-component#2]
ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.afval_pmd fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 261, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 441, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/acv/sensor.py", line 238, in update
    self._reader.update()
  File "/config/custom_components/acv/sensor.py", line 138, in update
    address_id = self._find_unique_address_id()
  File "/config/custom_components/acv/sensor.py", line 164, in _find_unique_address_id
    return response['dataList'][0]['UniqueId']
TypeError: 'NoneType' object is not subscriptable

**Comment by Cadsters** [comment]
Problem solved, probably caused by api-server maintenance.
